site_name: QPS-Infra

pages:
    - Overview: index.md
    - Installation Guide: install-guide.md
    - Configuration Guide: config-guide.md
    - User Guide: user-guide.md
    - FAQ: faq.md

theme:
  name: 'material'
repo_url: https://github.com/qaprosoft/qps-infra
repo_name: Github
